version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  supertokens:
    image: supertokens/supertokens-postgresql
    restart: always
    ports:
      - "3567:3567"